--- # This is an Ansible script to deploy nextcloud on a desired number of machines.

- hosts: prometheus
  user: root
  gather_facts: true
  vars_files: ./vars.yaml
  tasks:
    - name: Use https instead of http
      lineinfile:
        path: "{{ base_directory }}/nextcloud/html/config/config.php"
        regexp: ^\'overwriteprotocol.(*)$
        line: "'overwriteprotocol' => 'https'"
        backrefs: yes
