version: '3.8'
services:
   nginx:
     networks:
       nginx:
       drive:
         ipv4_address: ${NGINX_IP}
#===================================
   db:
     networks:
       drive:
         ipv4_address: ${DB_IP}
#===================================
   app:
     networks:
       nextcloud:
       drive:
         ipv4_address: ${APP_IP}
#===================================
 
 
networks:
#------- internet access ---------------------------------------
 
   nginx:
   nextcloud:
 
#------- internal access ---------------------------------------
   drive:
     internal: true
     ipam:
       driver: default
       config:
         - subnet: ${PRIVATE_SUBNET}
